install: gradle wrapper --gradle-version 4.7

language: java

jdk:
  - oraclejdk8

before_install:
  - chmod +x gradlew

script:
  - ./gradlew build codeCoverageReport --stacktrace

after_success:
  - bash <(curl -s https://codecov.io/bash)
